### ISSUE TITLE
Parsing dubinsrejoin.onnx (VNN-Comp 2022)

### ISSUE THREAD

**Issue by phK3** [vas-group-imperial/VeriNet#3]
When running VeriNet on the dubins_rejoin instances of VNN-Comp 2022 using
`benchmark(result_path, benchmark_path, instances_csv_path, input_shape=(8,), transpose_fc_weights=False)`, I get the following error:

`ValueError: Expected at least one connection to non-input node: VeriNetNNNode(idx: 1, op: Linear(in_features=256, out_features=8, bias=True), to: [2], from: [])`

The error gets thrown at VeriNet/verinet/sip_torch/sip.py, line 337, in _process_node.

Parsing for other networks works fine.

Thanks in advance for your help.

**Comment by pat676** [comment]
Hi, 

The ONNXParser uses strings to identify the input nodes. It provides some default input names which cover most cases; however, dubinsrejoin.onnx seems to have a non-standard name. 

There are a few solutions for automatically inferring input nodes from the ONNX model. However, we do not actively maintain this repo anymore besides small bug fixes; thus a fix will most likely not be implemented in the near future. 

My proposed solution is to change line 69 of benchmark.py from 

`model_onnx = ONNXParser(model_path)`

to:

`model_onnx = ONNXParser(model_path, input_names= ["dense_input"], transpose_matmul_weights=True)`

Note that I also added "transpose_matmul_weights=True" which I believe is necessary for this benchmark. 

Hope this helps!

**Comment by phK3** [comment]
It worked, when I changed line 74 in benchmark_vnnlib.py to

`ONNXParser(model_path, input_names=["dense_input"], transpose_fc_weights=True)`

(using `transpose_fc_weights`) if the `model_path` contains `dubinsrejoin`.

Thanks for your help!

**Comment by pat676** [comment]
Great! I'm closing this issue then
