### ISSUE TITLE
Outdated pipflie.lock

### ISSUE THREAD

**Issue by MarcelBulpr** [vas-group-imperial/VeriNet#8]
The pipfile.lock is outdated, not all packages are still in the public repositories, so the installation fails.
Ignoring the file does not work either since the most up-to-date version of xpress causes problems during runtime.
Additionally, dnnv has a requirement of `onnx<1.11` for both version `0.5.1` and the most up-to-date one.
Lastly, new versions of protobuf throw the following error.

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

It would be important to have an up-to-date lock file available for ease of use.

**Comment by pat676** [comment]
Hi, 

Thanks of the feedback. 

We are not actively maintaining this version of VeriNet anymore; thus I cannot implement any major fixes. However, I've tried to implement a workaround. 

1. I've removed all references to dnnv. This may limit the supported network architectures and slightly reduce the performance, but should usually be unnoticeable. 
2. For the protobuf message, I suggest setting the global variable PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python as suggested; the ONNX model is usually parsed only once and this is a relatively small part of the total runtime in most cases. 
3. I've deleted the outdated Pipfile.lock. 
4. I can't reproduce any Xpress errors. If this error still persists, could you please add a more detailed description of the error? 

Please pull the new version of the main branch. Hope this helps!

**Comment by MarcelBulpr** [comment]
Thank you, this already helps a lot.
